project_id = "cgbtlpipjxnbhugzulzl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-bombom-image]
verify_jwt = false