// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgbtlpipjxnbhugzulzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnYnRscGlwanhuYmh1Z3p1bHpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjM5MDMsImV4cCI6MjA3MTA5OTkwM30.d2whgdvHqM8mp-Lx7MGTwK3wSEis8GCCXcv-nq_GNE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});